### ISSUE TITLE
Staff?

### ISSUE THREAD

**Issue by Pacerier** [Rob--W/pdfjs-telemetry#1]
Are you working for Mozilla?

**Comment by Rob--W** [comment]
Not at the time that this repository was created, but now I do.
This telemetry is only for the official PDF.js Chrome extension for Google Chrome, and is not affiliated with Mozilla. The logic has passed code review and is part of the PDF.js code base, see https://github.com/mozilla/pdf.js/blob/master/extensions/chromium/telemetry.js and https://github.com/mozilla/pdf.js/pull/7370

Why do you ask?
